name: demo_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  flutter_datetime_picker_plus: ^2.1.0 
  image_picker: ^1.0.7
  open_file: ^3.3.2
  provider: ^6.1.2
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  # path: ^1.8.3
  intl: ^0.17.0
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  pagination_flutter: ^0.0.8
  toastification: ^2.0.0

  # MAP
  google_maps_flutter: ^2.6.0
  location: ^6.0.1
  flutter_polyline_points: ^2.0.0
  geocoding: ^3.0.0
  geolocator: ^11.0.0

  # PERMISSION
  permission_handler: ^11.3.1

  badges: ^3.1.2   
  curved_navigation_bar: ^1.0.3

  google_sign_in: ^6.2.1
  # FIREBASE
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  firebase_messaging: ^14.7.20
  firebase_in_app_messaging: ^0.7.4+18
  firebase_storage: ^11.6.10
  #VNPAY
  vnpay_flutter: ^1.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  # LOGO
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^2.0.0

flutter_launcher_icons: 
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/appLogo.png"
  adaptive_icon_background: "#ffffff"

flutter:

  assets:
    - assets/images/
    - assets/images/products/
    - assets/icons/

  uses-material-design: true
